### ISSUE TITLE
Radio station works in VLC & Firefox but is broken on radio-browser

### ISSUE THREAD

**Issue by biz411** [segler-alex/av-stream-info-rust#12]
Station: [KYRS](https://www.radio-browser.info/history/d782252d-dc1e-48a2-a5b0-77f867a997a5) is broken on radio-browser. [KYRS website](https://kyrs.org/).

The [Icecast Stream](https://nustream.pacificaservice.org:9000/kyrs_128) plays in the Firefox browser. It might be possible that your servers are GEO blocked. The stream is located in the United States. There are a large number of radio stations on that [Icecast server](https://nustream.pacificaservice.org:9000/) and I'm not sure that all of them are in the database.

The stream URL does not play on the radio-browser website with the Firefox browser. However, it does play in VLC. Sometimes the stream URL fails to connect in VLC on the first attempt, but on subsequent attempts it does connect.

One other unrelated note... It would be super awesome if you had a stream link on the radio station detail page so we can listen in the browser from the detail page. It would also be awesome if you had clickable tags on the detail page.

Also... When I submitted this station, the confirmation page had a link to this GitHub page to submit bugs. However, not knowing that I would need that link, I didn't bookmark it. I had to submit a "test" station to see that link again. It would be helpful if that link was in an obvious and easy to find location... possibly on each radio station detail page?

**Comment by Pryodon** [comment]
Station KYRS is in the process of moving to a new physical location. They should be streaming again in about 2 weeks or less.

**Comment by Pryodon** [comment]
This station will not play in radio browser page. However, if you click the "save" button, it starts playing.

The station is back online but was removed from the database so I entered it again. Hopefully it will work this time. I really don't want to have to enter all of that info again.

https://www.radio-browser.info/history/93e7afa1-5f43-44a5-88c2-063ff1569109
