### ISSUE TITLE
Broken recognition for JTR radio

### ISSUE THREAD

**Issue by k-kirill** [segler-alex/av-stream-info-rust#2]
The following stream is mistakenly recognized as "broken": https://jtradio.pro/playlists/live192.m3u
It is for "Jesus True Radio" and it used to work a few months ago.
VLC can play it without any issues.

**Comment by onurbi** [comment]
The stream http://media-ice.musicradio.com/ClassicFM-M-Relax  could not be recognized.
VLC-Player and Fritzbox can play it.

**Comment by kekukui** [comment]
@onurbi - Try http://icecast.thisisdax.com/ClassicFM **(or)** http://icecast.thisisdax.com/ClassicFM.m3u
[ as shown on http://media-ice.musicradio.com ]

icon: http://icecast.thisisdax.com/image/favicon.ico

**Comment by onurbi** [comment]
http://media-ice.musicradio.com/ClassicFM-M-Relax
and 
http://icecast.thisisdax.com/ClassicFM
are different senders with different programm!

The last one is a standard broadcast sender with news every hour and ads.
The first one has no ads. Therefore I prefer the first one.

**Comment by segler-alex** [comment]
https://jtradio.pro/playlists/live192.m3u
does not give a result with an agent name that does contain "bot" or "crawl"
this is against the standard. they make a distinction for different requesters.
i think they did this deliberatelly to not get indexed. if you want this to change, you have to talk to them.
i cannot do anything about it, i will send the correct Header agent string "StreamCheckBot"
