### ISSUE TITLE
https stream with self-signed ssl cert treated as broken

### ISSUE THREAD

**Issue by sirrosh** [segler-alex/av-stream-info-rust#7]
Which is not a correct behavior on my opinion.

**Comment by segler-alex** [comment]
i am now just marking streams with broken ssl instead of throwing them away. so users can still see that ssl is broken if they want to

**Comment by segler-alex** [comment]
it will be in server version 0.7.10

**Comment by sirrosh** [comment]
That's a wise decision, thank you!
