### ISSUE TITLE
JSON or XML output

### ISSUE THREAD

**Issue by micrococo** [segler-alex/av-stream-info-rust#9]
Could you add an option to get JSON or XML output in order to make it easy to parse by third party programs?

**Comment by segler-alex** [comment]
i do not understand your question.
this is a library to be used by other rust programs.

if you are talking about the API at api.radio-browser.info, this does already have JSON, XML and many more supported output formats.

**Comment by segler-alex** [comment]
please give your use case if you think i did not answer correctly

**Comment by micrococo** [comment]
Hi. It can be used to complete stations metadata. For example, say that I'm developing a GUI and I see that one station doesn't have any tags but `av-stream-info` shows that it has some. I can add a button to call `av-stream-info` and add the tags with one click. I have checked the output of `av-stream-info` for some stations without tags and sometimes it shows they have some.

**Comment by micrococo** [comment]
I've made a Python script to extract the headers info. It was my fault not noticing that `av-stream-info` wasn't meant to be used as an standalone utility. Thanks.
